import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/moleculs/navbar";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <h3>CHOOSE YOUR RESUME TEMPLATE</h3>
      <h4>Remember, you can always change your template later on.</h4>
      <div className="flex gap-5 flex-wrap justify-center">
        <img src="/resum1.png" className="bg-red-500 w-455" alt="porto1" />
        <img src="/resum1.png" className="bg-red-500 w-455" alt="porto1" />
        <img src="/resum1.png" className="bg-red-500 w-455" alt="porto1" />
        <img src="/resum1.png" className="bg-red-500 w-455" alt="porto1" />
        <img src="/resum1.png" className="bg-red-500 w-455" alt="porto1" />
        <img src="/resum1.png" className="bg-red-500 w-455" alt="porto1" />
        <img src="/resum1.png" className="bg-red-500 w-455" alt="porto1" />
        <img src="/resum1.png" className="bg-red-500 w-455" alt="porto1" />
      </div>
      <div className="flex justify-center">
        <button
          type="button"
          className="my-5 py-3 px-10 inline-flex items-center  border border-transparent text-xs font-medium rounded shadow-sm text-indigo-600 border-indigo-600 hover:bg-indigo-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
        >
          Skip
        </button>
      </div>
    </div>
  );
}
